### ISSUE TITLE
Update documentation for better way to get Toggl Workspace ID

### ISSUE THREAD

**Issue by supremebeing7** [supremebeing7/time_log_robot#36]
http://i.imgur.com/YqQLEAr.png
- Toggl Home > (hamburger menu) > Workspace Settings
- Select the workspace you want
- Workspace ID will be in the URL: https://www.toggl.com/app/workspaces/#{TOGGL_WORKSPACE_ID}/settings

Thanks @ekluff for the tip.

**Comment by l0010o0001l** [comment]
Is this about finding a more optimal/faster/better "way" to fetch a Toggl Workspace ID? 

Or is this issue moreso about updating the documentation so that it has more clarity?

**Comment by supremebeing7** [comment]
The latter. Also, the `curl` command in the README didn't even work for me last time I tried it.

**Comment by l0010o0001l** [comment]
https://github.com/supremebeing7/time_log_robot/pull/46

**Comment by supremebeing7** [comment]
![Mind blowing](http://www.reactiongifs.com/wp-content/uploads/2013/10/tim-and-eric-mind-blown.gif)

**Comment by supremebeing7** [comment]
Fixed by #46
